<?php
/** @var \Pronko\BannerWidget\Block\Banner $block */
?>
<div class="widget block-pronko-banner">
	<!-- this class is the widget -->
    <div class="page-header services-page-header"> 
    	<!-- this is the service main container -->
        <h1 class="title"><?= $block->escapeHtml($block->getData('title')); ?></h1>
        <div class="subtitle">
            <p><?= $block->escapeHtml($block->getData('subtitle')); ?></p>
        </div>
    </div>
</div>